version: '2'
services:
  postgres:
    container_name: bs_bingo_postgres
    image: postgres
    # command: postgres -c 'max_connections=8'
    environment:
      POSTGRES_DB: bs_bingo
      POSTGRES_USER: bs_bingo
      POSTGRES_PASSWORD: muchsecretwow
    ports:
      - '8433:5432'
